# Generated by Django 5.2.6 on 2025-09-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='comment',
        ),
    ]
